apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-huynn
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # có Recycle nữa,Retain là duy trì (nghĩa là xóa pvc đi thì pv đc Release và vẫn còn)
  storageClassName: local-storage
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /share-folder
    server: 10.0.0.3 # NAS công ty 
