apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: pv-huynn #phải khớp với volume name
  volumes:
    - name: pv-huynn
      persistentVolumeClaim:
        claimName: pvc-huynn
