apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-huynn
  namespace: pv-pvc-huynn
spec:
  volumeName: pv-huynn
  accessModes:
    - ReadWriteOnce # ReadWriteMany giá trị này phải khớp vs PV 
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage # storage class phải khớp với pv thì pvc mới bound đc vào pv
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}
