apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: Group
  name: manager # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io


# -------------------------------------------------------

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: role-grantor
# rules:
# - apiGroups: ["rbac.authorization.k8s.io"]
#   resources: ["rolebindings"]
#   verbs: ["create"]
# - apiGroups: ["rbac.authorization.k8s.io"]
#   resources: ["clusterroles"]
#   verbs: ["bind"]
#   # omit resourceNames to allow binding any ClusterRole
#   resourceNames: ["admin","edit","view"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: role-grantor-binding
#   namespace: user-1-namespace
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: role-grantor
# subjects:
# - apiGroup: rbac.authorization.k8s.io
#   kind: User
#   name: user-1
