apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tester
  name: pod-reader
rules:
- apiGroups: ["rbac.authorization.k8s.io"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

  # at the HTTP level, the name of the resource for accessing ConfigMap
  # objects is "configmaps"
  # resources: ["configmaps"]
  # resourceNames: ["my-configmap"]
  # verbs: ["update", "get"]
